---
- name: Create certs working directory
  ansible.builtin.file:
    path: /etc/elasticsearch/certs
    state: directory
    owner: root
    group: elasticsearch
    mode: "0750"
  tags: [es_certs, es_certs_ca]

- name: Generate CA (elastic-stack-ca.p12)
  ansible.builtin.command:
    cmd: >
      /usr/share/elasticsearch/bin/elasticsearch-certutil ca
      --out /etc/elasticsearch/certs/elastic-stack-ca.p12
      --pass "{{ elastic_cert_password }}"
    creates: /etc/elasticsearch/certs/elastic-stack-ca.p12
  tags: [es_certs, es_certs_ca]

- name: Generate transport certificate (elastic-certificates.p12)
  ansible.builtin.command:
    cmd: >
      /usr/share/elasticsearch/bin/elasticsearch-certutil cert
      --ca /etc/elasticsearch/certs/elastic-stack-ca.p12
      --ca-pass "{{ elastic_cert_password }}"
      --out /etc/elasticsearch/certs/elastic-certificates.p12
      --pass "{{ elastic_cert_password }}"
    creates: /etc/elasticsearch/certs/elastic-certificates.p12
  tags: [es_certs, es_certs_transport]

- name: Fetch transport cert to the control node's role files
  ansible.builtin.fetch:
    src: /etc/elasticsearch/certs/elastic-certificates.p12
    dest: "{{ role_path }}/files/elastic-certificates.p12"
    flat: true
  tags: [es_certs, es_certs_fetch]