---
- name: Setup Elasticsearch
  hosts: tag_Hostgroup_es_node
  become: true
  vars:
    common_hostname: es-node
    common_type: 'elasticsearch'
    network_host: "0.0.0.0"
  roles:
    - common
    - elasticsearch